# Config file for GFlows.
# See https://github.com/jbrunton/gflows/wiki/Configuration for options.
githubDir: .github
templates:
  engine: ytt
  defaults:
    libs:
      - workflow-configuration
    dependencies:
     - https://raw.githubusercontent.com/CoverGo/workflow-check/v1.8/.gflows
   #  - git@github.com:CoverGo/gflows.git/.gflows
