#@ load("@ytt:data", "data")
#@ load("integration-tests-legacy-steps.lib.yml", "integration_tests_legacy_steps")
#@ load("workflows.lib.yml", "pull_request_defaults")

name: Run integration tests
"on": #@ pull_request_defaults(data.values.git)
jobs:
  integration-tests-legacy-small:
    name: Run legacy integration small tenants tests
    runs-on: #@ data.values.integration_tests_legacy.runner
    steps: #@ integration_tests_legacy_steps(data.values.integration_tests_legacy.repository,[data.values.github_registry,data.values.alicloud_registry], data.values.integration_tests_legacy.environment, data.values.integration_tests_legacy.test_suites.small_tenants)
  integration-tests-legacy-big:
    name: Run legacy integration big tenants tests
    runs-on: #@ data.values.integration_tests_legacy.runner
    steps: #@ integration_tests_legacy_steps(data.values.integration_tests_legacy.repository, [data.values.github_registry,data.values.alicloud_registry], data.values.integration_tests_legacy.environment, data.values.integration_tests_legacy.test_suites.big_tenants)
